services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'

  medicare:
    image: 'medicare'
    environment:
      - 'DB_HOST=mariadb'
      - 'DB_USER=myuser'
      - 'DB_PASSWORD=verysecret'
    volumes:
      - ./uploads:/tmp/uploads