name: Build and Push to AWS ECR

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Spring Boot Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/libs/

  build_docker_image:
    name: Build Docker Image and Push to ECR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build/libs/

      - name: Build, tag, and push the image to ECR
        id: build-image
        env:
          IMAGE_TAG: ${{  steps.login-ecr.outputs.registry  }}/${{ secrets.REPO_NAME }}:latest
        run: |
          echo "Building docker container"
          docker build -t $IMAGE_TAG .
          echo "Pushing image to ECR"
          docker push $IMAGE_TAG
          echo "::set-output name=$IMAGE_TAG"
